version: '2.0'
services:
  post_db:
    image: csergey88/mongodb:latest
    volumes:
      - post_db:/data/db
    networks:
      - reddit
    ports:
      - 27017:27017
  ui:
    image: csergey88/ui:latest
    ports:
      - 9292:9292/tcp
    networks:
      - reddit
  post:
    image: csergey88/post:latest
    networks:
      - reddit
  comment:
    image: csergey88/comment:latest
    networks:
      - reddit
  prometheus:
    image: csergey88/prometheus
    ports: 
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - reddit
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - reddit

volumes:
  post_db:
  prometheus_data:

networks:
  reddit: